baseURL: 'https://ogobrecht.com/'
defaultContentLanguage: en
languages:
  en:
    weight: 1
    languageName: English
    translationHint: Show content in English
    commentHint: Comments are only available in English
    title: Ottmar’s Notes
    params:
      description: Mainly about Oracle APEX and PL/SQL
    menu:
      main:
        - name: Home
          url: /
          weight: 10
        - name: APEX
          url: /tags/apex/
          weight: 20
        - name: PL/SQL
          url: /tags/pl/sql/
          weight: 30
        - name: Open Source Projects
          url: /tags/open-source-project/
          weight: 40
        - name: Post Archive
          url: /archive/
          weight: 50
        - name: About
          url: /about/
          weight: 60
      legal:
        - name: Imprint
          url: /imprint/
          weight: 10
        - name: Privacy Statement
          url: /privacy-statement/
          weight: 20
  de:
    weight: 2
    languageName: Deutsch
    translationHint: Inhalt in Deutsch anzeigen
    title: Ottmar’s Notizen
    params:
      description: Hauptsächlich über Oracle APEX und PL/SQL
    menu:
      main:
        - name: Startseite
          url: /
          weight: 10
        - name: APEX
          url: /tags/apex/
          weight: 20
        - name: PL/SQL
          url: /tags/pl/sql/
          weight: 30
        - name: Open-Source-Projekte
          url: /tags/open-source-project/
          weight: 40
        - name: Beitragsarchiv
          url: /archiv/
          weight: 50
        - name: Über
          url: /ueber/
          weight: 60
      legal:
        - name: Impressum
          url: /impressum/
          weight: 10
        - name: Datenschutz-Erklärung
          url: /datenschutz-erklaerung/
          weight: 20
paginate: 100
pygmentsCodefences: true
pygmentsUseClasses: true
enableRobotsTXT: true
disableAliases: false
metaDataFormat: yaml
publishDir: public
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ''
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
params:
  rssLimit: 20
  author:
    name: Ottmar Gobrecht
    email: ottmar.gobrecht@gmail.com
    twitter: "@ogobrecht"
    url: /about/
    socialMedia:
      - name: GitHub
        url: 'https://github.com/ogobrecht'
        weight: 10
      - name: Twitter
        url: 'https://twitter.com/ogobrecht'
        weight: 20
      - name: XING
        url: 'https://xing.com/profile/Ottmar_Gobrecht'
        weight: 30
permalinks:
  posts: '/:section/:year-:month-:day-:slug/'
taxonomies:
  tag: tags
outputs:
  home:
    - HTML
    - FEED
  section:
    - HTML
mediaTypes:
  application/rss:
    suffixes:
      - xml
outputFormats:
  FEED:
    mediatype: application/rss
    baseName: feed
